---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
    exclude_fingerprints:
      - e17e85f54d46f4cc69f318b220c36c1a        
  eslint:
    enabled: false
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- client/
- config/
- coverage/
- db/
- lib/assets/
- spec/
- tmp/
- vendor/
- .idea/
- devServer.js
- gulpfile.babel.js
- karma.conf.js
- webpack.config.js
